# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    acme_user.registration.form.type:
        class: AppBundle\Form\UserType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias:  acme_user_registration }
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
